{% set version = "3.3.17" %}

package:
  name: breezy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/breezy/breezy-{{ version }}.tar.gz
  sha256: 5d2f45cd22e908b96833a4d424bcffc50593c2630b942ebc590280eb1f83410a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=60
    - setuptools-rust
    - setuptools-gettext >=0.1.4
    - cython >=0.29
    - packaging
    - pip
  run:
    - python
    - configobj
    - fastbencode
    - patiencediff
    - merge3
    - dulwich >=0.21.6
    - urllib3 >=1.24.1
    - pyyaml

test:
  imports:
    - breezy
  commands:
    - brz --help
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/breezy-team/breezy
  summary: Friendly distributed version control system
  license: GPL-2.0-or-later
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - danielnachun
