schema_version: 1

context:
  version: "3.3.21"

package:
  name: breezy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/breezy/breezy-${{ version }}.tar.gz
  sha256: 70a5a810690ad8d5def1798a1351e7588be7f89f821eb7a6fae277aacd33d3be

build:
  number: 0
  skip: win
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
  host:
    - python
    - setuptools >=60
    - setuptools-rust
    - setuptools-gettext >=0.1.4
    - cython >=0.29
    - packaging
    - pip
  run:
    - python
    - configobj
    - fastbencode
    - patiencediff
    - merge3
    - dulwich >=0.21.6
    - urllib3 >=1.24.1
    - pyyaml

tests:
  - python:
      imports:
        - breezy
  - requirements:
      run:
        - pip
        - python
    script:
      - brz --help
      - pip check

about:
  summary: Friendly distributed version control system
  license: GPL-2.0-or-later
  license_file:
    - THIRDPARTY.yml
    - COPYING.txt
  homepage: https://github.com/breezy-team/breezy

extra:
  recipe-maintainers:
    - danielnachun
